### ISSUE TITLE
Decoding Address from Script

### ISSUE THREAD

**Issue by teb02** [bip70/bip70-php#13]
In the example it outputs a script hex. Is it possible to convert this into a bitcoin address? If so would I need to use another repository? I tried using the Bit-Wasp/bitcoin-php repository but I can't figure out how to convert the script hex into a address.

**Comment by afk11** [comment]
I thought about having a concrete dependency on bitcoin-php, but it's better dependency-wise to keep them separate.

```php
// I think this works from 0.0.35 on
$script = ScriptFactory::fromHex($hexScript);
$addressCreator = new AddressCreator();
$address = $addressCreator->fromOutputScript($script);
```

```php
// If you're using 0.0.34
$script = ScriptFactory::fromHex($hexScript);
$address = AddressFactory::fromOutputScript($script);
```

**Comment by teb02** [comment]
Thank you, this solved my problem
