### ISSUE TITLE
Syntax error php 7.0

### ISSUE THREAD

**Issue by boooyu44** [bip70/bip70-php#6]
Trying this library on php 7.0:

`vendor\bip70\bip70\src\Client\PaymentRequestInfo.php`

> ["Parse error: syntax error, unexpected '?'"

```
/**
     * @return null|PathValidationResult
     */
    public function pathValidation(): ?PathValidationResult
    {
        return $this->validationResult;
    }
}

```

**Comment by boooyu44** [comment]
It seems to work without "?". Why is "?" there?
Some new PHP feature or typo?

**Comment by afk11** [comment]
Ah,that's something from 7.2. Maybe I should hold back on that :/

https://wiki.php.net/rfc/nullable_types

Will happily accept a PR replacing `?T` with `null|T` in phpdoc, and `T $t = null` in the input signature.. Pity about those return types though :P

can't wait for 7.2!

**Comment by boooyu44** [comment]
Unfortunately i have no full dev setup right now. Would be great if you could fix it.

If i were you and have public project i'd base all development at maximum 7.0x - this is the version Debian ships with. Quite many stable systems run on it -even though people use newest on their development hosts

I'd be very very thankful if you can fix it asap, as bitpay is shipping API update and we can no longer get direct addresses - forced to do workarounds. I haven't seen any other library that can handle bip70 data extraction except of yours.

**Comment by afk11** [comment]
Cool, I'll tag that fix now. https://github.com/bip70/bip70-php/pull/7

What type of solution will you move to? Curious how this project might be able to help, but it doesn't come with payments monitoring functionality, just the pure library for now.

btcpayserver could also be a good fit - self hosted, community lead, and you can hook it up to an exchange to do sells (at least, I think that's how that part works) It probably ticks most of the boxes, though its .NET.

**Comment by boooyu44** [comment]
At this moment i will stick to bitpay. I will just create invoice using their api and extract their BIP70 url and then use this library to to get the real address. I'm just afraid that my users will not be able to understand this new BIP70 thing and forcing them to move to another wallet (with BIP70 support) is just disaster. So i plan to display pure address to them.

**Comment by afk11** [comment]
Nice! I think I saw they were trying to kill off protobuf support as well, so some day that might break this library. https://github.com/krillionaire/BIP-Pay/blob/master/js/popup.js this shows how you can look up BIP21 uri's using the invoice ID - could be a useful backup :+1:

**Comment by afk11** [comment]
Tagged v0.0.4 to fix this issue. A few tweaks to the exceptions thrown by the lib, but nothing breaking.
